config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conversations do
    resources :messages

    collection do
      get :inbox
      get :all, action: :index
      get :sent
      get :trash
    end
  end

  root to: 'conversations#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def name
    "User #{id}"
  end

  def mailboxer_email(object)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def inbox
    @conversations = current_user.mailbox.inbox
    render action: :index
  end

  def sent
    @conversations = current_user.mailbox.sentbox
    render action: :index
  end

  def trash
    @conversations = current_user.mailbox.trash
    render action: :index
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.mark_as_read(current_user)
    @message = Mailboxer::Message.new
  end

  def new
    @conversation = Mailboxer::Conversation.new
    @recipients = User.all - [current_user]
  end

  def create
    recipients = User.where(id: params[:user_ids])
    receipt   = current_user.send_message(recipients, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation

  def create
    current_user.reply_to_conversation(
      @conversation,
      params[:mailboxer_message][:body],
      nil,
      true,
      true,
      params[:mailboxer_message][:attachment]
    )
    redirect_to conversation_path(@conversation)
  end

  private

    def set_conversation
      @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/conversations/index.html.erb
<h1>Conversations</h1>

<%= link_to "New Conversation", new_conversation_path %>

<hr />

Inbox (<%= current_user.mailbox.inbox.unread(current_user).count %>) |
All Conversations (<%= current_user.mailbox.conversations.count %>) |
Sent (<%= current_user.mailbox.sentbox.count %>) |
Trash (<%= current_user.mailbox.trash.count %>)

<hr />

Total: <%= @conversations.count %>

<% @conversations.each do |conversation| %>
  <div>
    <% if conversation.is_unread?(current_user) %>
      <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
    <% else %>
      <%= link_to conversation.subject, conversation_path(conversation) %>
    <% end %>
  </div>
<% end %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <p><%= select_tag :user_ids, options_from_collection_for_select(@recipients, :id, :name), multiple: true %></p>

  <p><%= text_field_tag :subject, nil, placeholder: "Subject" %></p>
  <p><%= text_area_tag :body, nil, placeholder: "Your message goes here" %></p>

  <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<h4>Participants</h4>
<% @conversation.participants.each do |participant| %>
  <div><%= participant.name %></div>
<% end %>

<hr />

<% @conversation.receipts_for(current_user).each do |receipt| %>
  <div>
    <div><%= receipt.message.sender.name %> commented</div>
    <%= simple_format receipt.message.body %>

    <% if receipt.message.attachment? %>
      <strong>Attachment</strong>
      <%= link_to receipt.message.attachment.file.filename, receipt.message.attachment.url, target: :blank %>
    <% end %>
  </div>

  <hr />
<% end %>

<%= form_for @message, url: conversation_messages_path(@conversation) do |f| %>
  <div><%= f.text_area :body %></div>
  <div><%= f.file_field :attachment %></div>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messaging</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>